### ISSUE TITLE
Image not showing on redirect page

### ISSUE THREAD

**Issue by aalogics-sse** [apps-payfast/apps-payfast-magento2-extension#1]
Image in jpeg format and image in redirct.phtml file is png Please fix

![Screenshot from 2021-08-02 12-40-12](https://user-images.githubusercontent.com/87357504/127822721-9f1599fe-27d8-441b-bf50-3e6cba063fcc.png)
![Screenshot from 2021-08-02 12-40-36](https://user-images.githubusercontent.com/87357504/127822724-7db02500-49ac-48c3-aab3-1cc0bae5d610.png)

**Comment by arfeen** [comment]
The filename has been fixed now.

25eb68831661065461f38087d0e42e1c8f091bc5
